export { default as AddPlayersScreen } from './AddPlayers'
export { default as GameOverScreen } from './GameOver'
export { default as HomeScreen } from './Home'
export { default as RulesScreen } from './Rules'
export { default as StartGameScreen } from './StartGame'
export { default as TutorialScreen } from './Tutorial'